### ISSUE TITLE
Create initial htpasswd during init

### ISSUE THREAD

**Issue by MFAnderson** [dudadornelles/hop#3]
As a convenience method we should create a default htpasswd with an admin for users when `hop init` is called. This requires prompting the user for a password interactively because having passwords in your bash_history is very bad.

Ideally would use semi-decent crypto with https://github.com/danielsomerfield/go-strong-auth-plugin but until we get that working just use the default unsalted SHA.

**Comment by dudadornelles** [comment]
Closed via 3107abdde671e67508ce808ef48e7264be65f871
